//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppManager.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Add to auto generated groups).
        /// </summary>
        public static string ADD_TO_AUTO_GROUPS {
            get {
                return ResourceManager.GetString("ADD_TO_AUTO_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to group.
        /// </summary>
        public static string ADD_TO_TYPE {
            get {
                return ResourceManager.GetString("ADD_TO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Programs menu.
        /// </summary>
        public static string ALL_PROGS {
            get {
                return ResourceManager.GetString("ALL_PROGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string ALWAYS_ON_TOP {
            get {
                return ResourceManager.GetString("ALWAYS_ON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link manager.
        /// </summary>
        public static string APP_MANAGER {
            get {
                return ResourceManager.GetString("APP_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartUp.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string APP_TYPE_NAME {
            get {
                return ResourceManager.GetString("APP_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application groups.
        /// </summary>
        public static string APP_TYPES {
            get {
                return ResourceManager.GetString("APP_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string APPLICATION {
            get {
                return ResourceManager.GetString("APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string APPLICATIONS {
            get {
                return ResourceManager.GetString("APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications in group:.
        /// </summary>
        public static string APPS_IN_TYPE {
            get {
                return ResourceManager.GetString("APPS_IN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto group.
        /// </summary>
        public static string AUTO_GROUP {
            get {
                return ResourceManager.GetString("AUTO_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string AUTO_START {
            get {
                return ResourceManager.GetString("AUTO_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CHECK_FOR_UPDATE {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application data file.
        /// </summary>
        public static string EDIT_APP_DATA {
            get {
                return ResourceManager.GetString("EDIT_APP_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mouse activation.
        /// </summary>
        public static string ENABLE_ACT_PANEL {
            get {
                return ResourceManager.GetString("ENABLE_ACT_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter application name.
        /// </summary>
        public static string ENTER_APP_NAME {
            get {
                return ResourceManager.GetString("ENTER_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter application group name.
        /// </summary>
        public static string ENTER_APP_TYPE_NAME {
            get {
                return ResourceManager.GetString("ENTER_APP_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter command line arguments.
        /// </summary>
        public static string ENTER_CMD_ARGS {
            get {
                return ResourceManager.GetString("ENTER_CMD_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppManager error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry there is an unknown error in application.
        /// </summary>
        public static string ERROR_OCCUR {
            get {
                return ResourceManager.GetString("ERROR_OCCUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/Help.en-en.rtf.
        /// </summary>
        public static string HELP_FILE {
            get {
                return ResourceManager.GetString("HELP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for new version....
        /// </summary>
        public static string LOOK_FOR_NEW_VER {
            get {
                return ResourceManager.GetString("LOOK_FOR_NEW_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new application....
        /// </summary>
        public static string MNU_ADD_APP {
            get {
                return ResourceManager.GetString("MNU_ADD_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group....
        /// </summary>
        public static string MNU_ADD_APP_TYPE {
            get {
                return ResourceManager.GetString("MNU_ADD_APP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MNU_CLOSE {
            get {
                return ResourceManager.GetString("MNU_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove link to {0}.
        /// </summary>
        public static string MNU_DELETE {
            get {
                return ResourceManager.GetString("MNU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} group.
        /// </summary>
        public static string MNU_DELETE_TYPE {
            get {
                return ResourceManager.GetString("MNU_DELETE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}....
        /// </summary>
        public static string MNU_EDIT {
            get {
                return ResourceManager.GetString("MNU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to {0} application folder.
        /// </summary>
        public static string MNU_GOTO {
            get {
                return ResourceManager.GetString("MNU_GOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide StartUp.
        /// </summary>
        public static string MNU_HIDE {
            get {
                return ResourceManager.GetString("MNU_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications manager....
        /// </summary>
        public static string MNU_MANAGEAPP {
            get {
                return ResourceManager.GetString("MNU_MANAGEAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {0}....
        /// </summary>
        public static string MNU_RENAME {
            get {
                return ResourceManager.GetString("MNU_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {0} group....
        /// </summary>
        public static string MNU_RENAME_APP_TYPE {
            get {
                return ResourceManager.GetString("MNU_RENAME_APP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run {0} with arguments....
        /// </summary>
        public static string MNU_RUN_WITH_ARGS {
            get {
                return ResourceManager.GetString("MNU_RUN_WITH_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        public static string MNU_SETTINGS {
            get {
                return ResourceManager.GetString("MNU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show StartUp.
        /// </summary>
        public static string MNU_SHOW {
            get {
                return ResourceManager.GetString("MNU_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application.
        /// </summary>
        public static string NEW_APP {
            get {
                return ResourceManager.GetString("NEW_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You use {0} latest version..
        /// </summary>
        public static string NO_NEW_VERSION {
            get {
                return ResourceManager.GetString("NO_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show application data folder.
        /// </summary>
        public static string OPEN_APP_DATA {
            get {
                return ResourceManager.GetString("OPEN_APP_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartUp&apos;s page on CodePlex.
        /// </summary>
        public static string PAGE_ON_CP {
            get {
                return ResourceManager.GetString("PAGE_ON_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove link to
        ///{0}
        ///?.
        /// </summary>
        public static string QUEST_DEL_APP {
            get {
                return ResourceManager.GetString("QUEST_DEL_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///{0}
        ///group?.
        /// </summary>
        public static string QUEST_DEL_APP_TYPE {
            get {
                return ResourceManager.GetString("QUEST_DEL_APP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add applications from these folders?.
        /// </summary>
        public static string QUEST_FIRST_SCAN {
            get {
                return ResourceManager.GetString("QUEST_FIRST_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Launch.
        /// </summary>
        public static string QUICK_LAUNCH {
            get {
                return ResourceManager.GetString("QUICK_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start menu.
        /// </summary>
        public static string QUICK_START {
            get {
                return ResourceManager.GetString("QUICK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan &quot;All Programs&quot; menu.
        /// </summary>
        public static string SCAN_ALL_PROGS {
            get {
                return ResourceManager.GetString("SCAN_ALL_PROGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan &quot;Quick Launch&quot; menu.
        /// </summary>
        public static string SCAN_QUICK_LAUNCH {
            get {
                return ResourceManager.GetString("SCAN_QUICK_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group to add applications to.
        /// </summary>
        public static string SELECT_APP_GROUP {
            get {
                return ResourceManager.GetString("SELECT_APP_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to my friends for testing, feature requests and help with translating into english..
        /// </summary>
        public static string SPECIAL_THANKS {
            get {
                return ResourceManager.GetString("SPECIAL_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string START_MINIMIZED {
            get {
                return ResourceManager.GetString("START_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not check for updates now. Try to check later..
        /// </summary>
        public static string UPDATE_CHECK_FAILED {
            get {
                return ResourceManager.GetString("UPDATE_CHECK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse activation only in corner.
        /// </summary>
        public static string USE_SHORT_ACT_PANEL {
            get {
                return ResourceManager.GetString("USE_SHORT_ACT_PANEL", resourceCulture);
            }
        }
    }
}
